### ISSUE TITLE
badge in readme indicates failing tests

### ISSUE THREAD

**Issue by matkoniecz** [troessner/reek#937] opened 2016-06-04 11:02 UTC
https://github.com/troessner/reek#overview

**Comment by troessner** [comment] 2016-06-04 14:48
Yeah, I think that's the same as #936 even though @mvz didn't really say why he opened the issue (der schlawiner!).

Looking at travis:

>> 
fatal: No commit specified?
bundler: failed to load command: mutant (/home/travis/build/troessner/reek/vendor/bundle/ruby/2.3.0/bin/mutant)
Mutant::Repository::RepositoryError: Command ["git", "log", "HEAD...master", "-L", "23,34:/home/travis/build/troessner/reek/lib/reek/ast/ast_node_class_map.rb"] failed!

As an alternative, we could check for the git branch in a subshell and update our .travis.yml:

>>
script: "bundle exec rake &&
        bundle exec ataru check &&
        (check_if_we_are_in_master && RUBY_THREAD_VM_STACK_SIZE=64000 bundle exec mutant --include lib --require reek --use rspec --since master --jobs 4 'Reek*')"

@mbj any advise from your side?

**Comment by mvz** [comment] 2016-06-04 15:31
Maybe we can move all that logic into a rake task?

**Comment by mvz** [comment] 2016-06-04 15:32
God yes that's a pretty contentless ticket I made there.

**Comment by troessner** [comment] 2016-06-04 15:50
Agree, we should have a "ci" rake task. I'd still like to pick @mbj brain since that seems like such  a common use case.

**Comment by troessner** [comment] 2016-06-11 09:26
Lets get #941 merged and then i'll fix this issue.

**Comment by mbj** [comment] 2016-06-11 19:39
> Agree, we should have a "ci" rake task. I'd still like to pick @mbj brain since that seems like such a common use case.

@troessner Is there a reproduction?

**Comment by troessner** [comment] 2016-06-11 19:57
This

>> bundle exec mutant --include lib --require reek --use rspec --since master --jobs 4 'Reek*'

will cause `mutant` to crash on master with:

>>
fatal: No commit specified?
/Users/timo/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/mutant-0.8.10/lib/mutant/repository.rb:47:in `touches?': Command ["git", "log", "HEAD...master", "-L", "23,34:/Users/timo/dev/reek/lib/reek/ast/ast_node_class_map.rb"] failed! (Mutant::Repository::RepositoryError)

"--since master" seems like a fairly common use case so I'm wondering if `mutant` provides an elegant fix for this that we fail to see right now?

**Comment by mbj** [comment] 2016-06-12 08:06
> We call mutant like this in our Rake task
> 
> bundle exec mutant --include lib --require reek --use rspec --since master --jobs 4 'Reek*'
> which will cause mutant to crash on master with:

Normally its just selecting the empty diff. I wonder why it causes problems for you. I used the exact same setting for a while, but recently changed to `--since HEAD~1` as this is more fine grained.

**Comment by mbj** [comment] 2016-06-12 08:14
I can reproduce it locally, maybe recent git changed behavior. Can you open an issue? It IMO should be a noop.

**Comment by troessner** [comment] 2016-06-12 10:46
Done @mbj

**Comment by mbj** [comment] 2016-06-12 11:48
@troessner Thx, looking to find another git CLI that works well in this case. Alternatively I've to parse the output of `git diff` intersecting it with the subjects, this would also be much faster, but also more work.

My OSS time is very limited, maybe you can consider to switch to `--since HEAD~1` meanwhile? Its agnostic to this case (but requires to build each commit, something I really like for other reasons).

**Closed** 2016-06-12 18:44 UTC
