### ISSUE TITLE
FeatureEnvy too curious about what's inside lambda expressions

### ISSUE THREAD

**Issue by andreaspixsy** [troessner/reek#1131] opened 2016-10-22 20:16 UTC
I ran reek on https://github.com/tueksta/webstats/blob/master/importer.rb
and I got this smell warning:

```
importer.rb -- 4 warnings:
  [10, 11, 12, 13, 14, 15, 16, 17, 18]:FeatureEnvy: Importer#initialize refers to 'arg' more than self (maybe move it to another class?) [https://github.com/troessner/reek/blob/master/docs/Feature-Envy.md]
...
```

In my opinion this is a false positive, as the args are not referred to by Importer#initialize at all: the lambda expressions should be considered by reek as yet another data entry as they will never be executed within the context of Importer#initialize - inspecting the the insides needs a different context, the one where it is actually called.

**Comment by tueksta** [comment] 2016-10-22 20:31
whoops, wrong account :)

well, I can also imagine not snooping on lambdas at all. is there some configuration to have them ignored?

**Comment by mvz** [comment] 2016-10-22 21:52
Hi, thanks for your bug report.

This is an interesting issue. First of all, I think Reek should probably consider each `arg` of each lambda as a separate entity. This would make the warning go away, since each `arg` only has one method called on it.

Second,

> as they will never be executed within the context of Importer#initialize

I'm afraid it's not really possible to determine this: If you're using `#each` with a block, that block is in a sense called in the context of the containing method. But some other method may take a block and just store it for later use. The same goes with lambda's.

In the end, though, it doesn't really matter when the block or lambda is called: If it doesn't really use any part of the Importer instance, why does it need to be in that class? Maybe it's better off in another class. In this case, you can consider creating classes `GoodReadsImportSource`, `ImdbImportSource`, etc.

**Comment by tueksta** [comment] 2016-10-22 22:11
I agree, what I did is not a good final solution. (I also want to avoid specialized importers, as this is considered data and not logic - only with strict separation I retain the flexibility of adding and removing ImportSources without changing code for better scaling. Moving away from lambdas to a more proper representation of what they are trying to achieve will also get rid of the reek warning.)

But anyway, even as an interims solution, I did not expect this smell to appear - by distinguishing variables according to the lambdas/procs/blocks they are created and used in the smell detection by reek would be much more refined, in my opinion.

**Comment by troessner** [comment] 2016-10-23 14:06
>> First of all, I think Reek should probably consider each arg of each lambda as a separate entity. This would make the warning go away, since each arg only has one method called on it.

Agreed, let's fix this.

**Comment by troessner** [comment] 2017-01-07 21:17
The original code is not available anymore.
@tueksta how can we reproduce this?

**Comment by tueksta** [comment] 2017-01-07 21:28
@troessner check out https://github.com/tueksta/webstats/commit/6aab3e2272e90a0d5e2fc0578bdaf06d6cfe47b9

**Comment by oliverklee** [comment] 2017-07-11 12:25
#1231 might be related.

**Comment by tueksta** [comment] 2017-09-04 12:55
definitely :)

**Comment by tueksta** [comment] 2017-09-04 13:44
btw: I can't reproduce the FeatureEnvy issue with the latest version of reek anymore, so I guess this issue can be closed and discussion move on to #1231

**Comment by mvz** [comment] 2017-09-04 13:53
Ok, closing this.

**Comment by mvz** [comment] 2017-09-04 15:27
Incidentally, I have checked and indeed the behavior of FeatureEnvy has changed

**Comment by mvz** [comment] 2017-09-04 16:35
OK, so the reason not emitting `:lambda` nodes 'fixed' this issue, is that without those nodes, each lambda expression counts as a method call on self.

**Comment by tueksta** [comment] 2017-09-04 16:48
While you're at it, you can fix the typo in this comment :) https://github.com/troessner/reek/blob/master/lib/reek/ast/builder.rb#L9

**Comment by mvz** [comment] 2017-09-04 16:56
@tueksta done 🙂 !

**Closed** 2018-06-22 07:54 UTC
Labels: defect
