### ISSUE TITLE
Flay | How to disable it or exclude some files from its analysis?

### ISSUE THREAD

**Issue by lflucasferreira** [troessner/reek#1494] opened 2019-10-21 21:11 UTC
Hi,

The Flay is pointing a DuplicateCode Smell in two files. I would like to ignore these files and increase the code score, but there is no documentation about how to disable/exclude this smell.

I tried to use *exclude_paths* but it is not working at all.

Could you please help me? I'm lost.

**Comment by mvz** [comment] 2019-10-21 22:03
Hi @lflucasferreira, this is the issue tracker for Reek, not Flay. I'm closing this as a duplicate of https://github.com/whitesmith/rubycritic/issues/321. If you're running Flay through rubycritic, that is the right place to ask.

**Closed by mvz** 2019-10-21 22:03 UTC
