### ISSUE TITLE
docs/Syntax.md is missing

### ISSUE THREAD

**Issue by x3qt** [troessner/reek#1291] opened 2018-01-10 14:54 UTC
### Description:
Usage of [do/end blocks with ensure/rescue/else](https://bugs.ruby-lang.org/issues/12906) throws syntax error which points to non existent page.

```
[14]:Syntax: This file has unexpected token kENSURE
[https://github.com/troessner/reek/blob/master/docs/Syntax.md]
```

### Environment:
- ruby 2.5.0
- reek 4.7.3

**Comment by x3qt** [comment] 2018-01-10 15:51
It seems that bug was introduced in #1220

**Comment by mvz** [comment] 2018-01-10 17:01
Thanks, @x3qt, we'll look into this.

**Comment by chastell** [comment] 2018-01-14 16:24
I think this is not as much a missing docs file as a case that shouldn’t get to the point of reporting smells, but rather blow up with a syntax error.

(In this particular case we’re using a Ruby 2.4 parser to parse a Ruby 2.5 source, and that’s the culprit, but in general I wouldn’t consider syntax errors as smells.)

**Comment by mvz** [comment] 2018-01-15 08:53
@chastell I think that makes sense since we handle encoding errors that way too.

**Comment by mvz** [comment] 2018-01-15 08:55
@troessner wdyt?

**Comment by troessner** [comment] 2018-01-15 09:22
@mvz @chastell fully agree with you here.

**Comment by krasnoukhov** [comment] 2018-05-14 17:58
FYI I'm seeing smells related to this check on codeclimate, but not locally. We're using the latest release version with Ruby 2.5

**Comment by troessner** [comment] 2018-05-14 19:14
@krasnoukhov could you please c&p the offending code here so we can reproduce it?

**Comment by krasnoukhov** [comment] 2018-05-14 20:30
@troessner Sure thing, I think a very minimal code that triggers the check could look like this:

```ruby
[].each do |x|
  puts x
rescue
end
```

**Comment by troessner** [comment] 2018-05-29 08:18
@krasnoukhov this should be fixed with Reek 5 which we'll also push on CodeClimate.

**Comment by mvz** [comment] 2018-06-20 05:51
@troessner Wait, what? We do the pushing to CodeClimate?

**Comment by troessner** [comment] 2018-06-21 05:49
@mvz as discussed in the other thread recently we dont apparently :-/

**Comment by troessner** [comment] 2018-06-21 13:15
@mvz wdyt about removing the syntax detector completely? Right now i cant even recall why we added that in the first place :)
I know its unrelated to the actual issue (that Reek blows up on innocuous code), but there's nothing keeping us from improving our error handling as well. As pointed out above, we probably should treat this like an EncodingError.

**Comment by troessner** [comment] 2018-06-21 14:35
To the actual problem, this code from above:

```Ruby
[].each do |x|
  puts x
rescue
end
```

works for me with Reek 4.8.1 and Ruby 2.3.1:

```
reek ~/Desktop/broken.rb
Inspecting 1 file(s):
.
```

Regarding:

```
(In this particular case we’re using a Ruby 2.4 parser to parse a Ruby 2.5 source, and that’s the culprit, but in general I wouldn’t consider syntax errors as smells.)
```

I just checked, we're using 2.5 at least now. @x3qt could you quickly check if that problem still exists for you with the latest Reek version?

**Comment by mvz** [comment] 2018-06-21 15:54
> we probably should treat this like an EncodingError.

Yes, that makes more sense than treating it like an artificial code smell.

**Comment by mvz** [comment] 2018-06-24 10:08
See #1355 and #1356.

**Comment by mvz** [comment] 2018-06-24 10:09
@x3qt the syntax error should no longer occur in the latest Reek codeclimate engine. Removing the Syntax 'smell' is tracked in #1355.

**Closed by mvz** 2018-06-24 10:09 UTC
Labels: defect

**Comment by mvz** [comment] 2018-06-24 10:32
@troessner ok, I'll see about taking over #1355.
