### ISSUE TITLE
Report unnecessary suppressions

### ISSUE THREAD

**Issue by jhubert** [troessner/reek#1152] opened 2016-12-03 01:36 UTC
Rubocop has a nice process where they let you know if you've unnecessarily suppressed a smell. It would be nice to have the same thing in reek so that my code doesn't end up littered with unnecessary comments while we refactor.

**Comment by mvz** [comment] 2016-12-03 09:46
Some work is already in progress on this. See #961 and #1060.

**Comment by mvz** [comment] 2020-02-01 09:21
Closing this as a duplicate of #961.

**Closed by mvz** 2020-02-01 09:21 UTC
Labels: feature
