### ISSUE TITLE
exclude_paths not getting picked up if current directory passed as argument

### ISSUE THREAD

**Issue by prpetten** [troessner/reek#1092] opened 2016-09-19 18:52 UTC
Belos is my `config.reek` file which is located in my home directory

``` Yaml
# config.reek Located in home directory

---
InstanceVariableAssumption:
  enabled: false
exclude_paths:
  - db
  - config
```

If I execute from the command line as shown below, I get the following results

``` Shell
$ reek
0 total warnings

$ reek .
app/controllers/api/v1/trackers_controller.rb -- 1 warning:
  [8]:InstanceVariableAssumption: Api::V1::TrackersController assumes too much for instance variable '@api_tracker' [https://github.com/troessner/reek/blob/master/docs/Instance-Variable-Assumption.md]
config/boot.rb -- 1 warning:
  [7]:IrresponsibleModule: DefaultOptions has no descriptive comment
db/migrate/20160819172640_create_trackers.rb -- 4 warnings:
  [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15]:FeatureEnvy: CreateTrackers#change refers to 't' more than self (maybe move it to another class?)
  [1]:IrresponsibleModule: CreateTrackers has no descriptive comment
  [2]:TooManyStatements: CreateTrackers#change has approx 14 statements
  [3]:UncommunicativeVariableName: CreateTrackers#change has the variable name 't'
db/migrate/20160819214127_install_audited.rb -- 3 warnings:
  [1]:IrresponsibleModule: InstallAudited has no descriptive comment
  [2]:TooManyStatements: InstallAudited#self.up has approx 20 statements
  [3]:UncommunicativeVariableName: InstallAudited#self.up has the variable name 't'
db/migrate/20160916030434_update_tracker_columns.rb -- 3 warnings:
  [1]:IrresponsibleModule: UpdateTrackerColumns has no descriptive comment
  [12]:TooManyStatements: UpdateTrackerColumns#down has approx 7 statements
  [2]:TooManyStatements: UpdateTrackerColumns#up has approx 7 statements
11 total warnings
```

Now if I comment out the first smell in `config.reek` like so:

``` yaml

---
#InstanceVariableAssumption:
#  enabled: false
exclude_paths:
  - db
  - config
```

And then rerun each, you see that the `reek .` was using that config file just not the exclude_paths portion.

``` Shell
$ reek
app/controllers/api/v1/trackers_controller.rb -- 1 warning:
  [8]:InstanceVariableAssumption: Api::V1::TrackersController assumes too much for instance variable '@api_tracker'
1 total warning

$ reek . 
app/controllers/api/v1/trackers_controller.rb -- 1 warning:
  [8]:InstanceVariableAssumption: Api::V1::TrackersController assumes too much for instance variable '@api_tracker'
config/boot.rb -- 1 warning:
  [7]:IrresponsibleModule: DefaultOptions has no descriptive comment
db/migrate/20160819172640_create_trackers.rb -- 4 warnings:
  [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15]:FeatureEnvy: CreateTrackers#change refers to 't' more than self (maybe move it to another class?)
  [1]:IrresponsibleModule: CreateTrackers has no descriptive comment
  [2]:TooManyStatements: CreateTrackers#change has approx 14 statements
  [3]:UncommunicativeVariableName: CreateTrackers#change has the variable name 't'
db/migrate/20160819214127_install_audited.rb -- 3 warnings:
  [1]:IrresponsibleModule: InstallAudited has no descriptive comment
  [2]:TooManyStatements: InstallAudited#self.up has approx 20 statements
  [3]:UncommunicativeVariableName: InstallAudited#self.up has the variable name 't'
db/migrate/20160916030434_update_tracker_columns.rb -- 3 warnings:
  [1]:IrresponsibleModule: UpdateTrackerColumns has no descriptive comment
  [12]:TooManyStatements: UpdateTrackerColumns#down has approx 7 statements
  [2]:TooManyStatements: UpdateTrackerColumns#up has approx 7 statements
12 total warnings
```

If this is working as intended, and I can definitely see an argument for that, if you would add that to the documentation, it would be helpful.

**Comment by troessner** [comment] 2016-09-19 20:24
Hmmm, that's debatable indeed. From my POV: If you have a config file in your home directory but are referring to project directories I'd expect absolute paths in there, not relative ones to the working directory.
But you're absolutely right, this should be part of our documentation so people don't trip over it. I'll add a paragraph over the next days, thanks for bringing this to our attention!

**Comment by prpetten** [comment] 2016-09-20 00:58
@troessner I agree with you, it just surprised me when I executed `$ reek .` from my home directory, that it didn't pick up the `exclude_paths`.

**Comment by prpetten** [comment] 2016-09-20 01:01
@troessner 
I think it was the line from the read me, that is particularly confusing:
So
```shell
reek
```
is the exact same thing as being explicit:
```shell
reek .
```shell

**Comment by mvz** [comment] 2016-09-20 07:42
@prpetten Wait, so you're running reek from your home directory, the exact same directory where your `config.reek` is located? And you have a directory `app` right below that?

@troessner it looks like something more is going on here, since `reek` and `reek .` appear to behave differently. I can confirm that they behave the same when the config is not in the home directory.

**Comment by prpetten** [comment] 2016-09-20 16:21
@mvz That's correct.

**Comment by markokajzer** [comment] 2016-11-04 03:37
Can confirm. Runnin `reek` in my projects root directory where also my config file is located yields 13 warnings while running `reek .` yields 51 warnings. The only thing that does not get picked up is the `exclude_paths` command which results in this difference. My config looks like this.

```yml
---

IrresponsibleModule:
  enabled: false

"app/workers":
  UtilityFunction:
    enabled: false

"spec/support":
  UncommunicativeMethodName:
    enabled: false

exclude_paths:
  - db
  - vendor
```

**Comment by mvz** [comment] 2016-11-04 08:04
@markokajzer is your project root directory also your home directory?

**Comment by markokajzer** [comment] 2016-11-04 08:07
Ah! The directory I executed reek in was `~/projects/foo/bar` and the config was on the root of _that_ folder.

**Comment by mvz** [comment] 2017-02-05 12:53
This should be fixed in master.

**Closed by mvz** 2017-02-05 12:53 UTC
Labels: defect, documentation
