### ISSUE TITLE
Global Exclusions?

### ISSUE THREAD

**Issue by jfelchner** [troessner/reek#349] opened 2014-12-12 21:39 UTC
I'm thinking I must just be missing this.  Is there a way to say that I would not like any smell detection on a certain subset of files?  Like `spec/factories/*.rb`?

**Comment by mvz** [comment] 2015-02-15 20:46
How about making this part of Reek 2.1?

**Comment by troessner** [comment] 2015-02-15 21:19
Good idea!

**Comment by mvz** [comment] 2015-05-17 05:37
@troessner are you still looking into this?

**Comment by troessner** [comment] 2015-05-17 09:20
>> @troessner are you still looking into this?

It's still on my todo list but I want to further look into the refactoring started in #395 - the issue is closed because i didnt want to have issues around for such vague tasks like "Refactor /core." But this refactoring is what I'm gonna do next.

Long story short: Feel free to take over this issue if you like, if not then yes, I'd come back to this issue somewhere in the future.:)

**Comment by troessner** [comment] 2015-06-30 21:24
Implemented in #550 - closing this.

**Closed by troessner** 2015-06-30 21:24 UTC
Labels: feature
