### ISSUE TITLE
Question: Should the『rescue => e』trigger a UncommunicativeVariableName ? 

### ISSUE THREAD

**Issue by fanjieqi** [troessner/reek#1136] opened 2016-11-10 03:06 UTC
Excuse me, I have no idea should the 『rescue => e』trigger a UncommunicativeVariableName.
『rescue => e』is very common in ruby coding, so I guess maybe it should not trigger a UncommunicativeVariableName.

_English is not my first language, Sorry for my grammar mistake._

**Comment by troessner** [comment] 2016-11-10 09:26
Reek reports `rescue => e` right now and I think it rightfully does so.

>>『rescue => e』is very common in ruby coding, so I guess maybe it should not trigger a UncommunicativeVariableName.

Sure. But you could make the same case for a lot of things we report, e.g.

`def foo; bar.map {|e| e.huhu  }; end`

even though it's clear what `e` points to.

**Comment by Drenmi** [comment] 2016-11-11 06:49
I think `rescue => e` is a horrible idiom, and I'm glad that we're starting to challenge the status quo. 😀 

Not only is that `e` uncommunicative, but we're also not stating anything about which exceptions we expect to see, which enables us to be lazy about our application design, and obscures our intentions (both to ourselves and to others.)

There are valid cases where we need to rescue from `StandardError`, but then we might as well spell that out, as was suggested by Thoughtbot in [this blog post](https://robots.thoughtbot.com/rescue-standarderror-not-exception#when-that39s-not-possible). 😊

(Note to self: I should probably add a cop for this in RuboCop.)

**Comment by troessner** [comment] 2016-11-12 20:15
I think the issue is pretty clear, closing this one.

**Closed by troessner** 2016-11-12 20:15 UTC

**Comment by philister** [comment] 2021-05-31 09:20
This is still a thing?

**Comment by mvz** [comment] 2021-05-31 10:26
@philister I'm not entirely sure what you want to know, but our standpoint on this has not changed.

**Comment by philister** [comment] 2021-06-01 07:14
@mvz Thanks! Thats fine for me.
