### ISSUE TITLE
UtilityFunction triggered on modules with 'extend self'

### ISSUE THREAD

**Issue by adrianbn** [troessner/reek#1023] opened 2016-08-20 20:42 UTC
I'm defining a set of methods inside a module via 

``` ruby
module Foo
  module Bar
    extend self
    def do_stuff
      # things
    end
  end
end
```

Reek triggers the UtilityFunction smell on those methods even though the behaviour should be the same as for:

``` ruby
module Foo
  module Bar
    class << self
      def do_stuff
        # things
      end
    end
  end
end
```

The latter won't trigger UtilityFunction as per https://github.com/troessner/reek/issues/112. Should 'extend self' also be supported here? 

Thanks!

**Comment by troessner** [comment] 2016-08-21 07:44
>> Reek triggers the UtilityFunction smell on those methods even though the behaviour should be the same as for:

It's not the same.
The second version will not define any instance methods on the class that includes the module, the first one will as you can quickly see for yourself in pry ;)
That's why the latter one doesn't report the smell but the first one does.

**Comment by mvz** [comment] 2016-08-21 09:36
> The second version will not define any instance methods on the class that includes the module, the first one will as you can quickly see for yourself in pry ;)
> That's why the latter one doesn't report the smell but the first one does.

However, the first version does have the same behavior as using `module_function`, which does block triggering of this smell.

**Comment by adrianbn** [comment] 2016-08-21 09:42
I thought the same as @mvz with regards `module_function` and `extend self`, which is part of the confusion with my original post, but I am not sure after checking it. This is `module_function`:

```
[1] pry(main)> module Foo
[1] pry(main)*   module_function
[1] pry(main)*   def stuff
[1] pry(main)*     puts 'in stuff'
[1] pry(main)*   end
[1] pry(main)* end
=> :stuff
[2] pry(main)> Foo.instance_methods
=> []
[3] pry(main)> Foo.methods.grep /stuff/
=> [:stuff]
[4] pry(main)> class Test
[4] pry(main)*   include Foo
[4] pry(main)* end
=> Test
[5] pry(main)> Test.instance_methods.grep /stuff/
=> []
[6] pry(main)> t = Test.new
=> #<Test:0x007fd26bab6c20>
[7] pry(main)> t.stuff
NoMethodError: private method `stuff' called for #<Test:0x007fd26bab6c20>
from (pry):14:in `__pry__'
```

versus the `extend self` option:

```
[1] pry(main)> module Bar
[1] pry(main)*   extend self
[1] pry(main)*   def stuff
[1] pry(main)*     puts 'in stuff'
[1] pry(main)*   end
[1] pry(main)* end
=> :stuff
[2] pry(main)> Bar.instance_methods
=> [:stuff]
[3] pry(main)> Bar.methods.grep /stuff/
=> [:stuff]
[4] pry(main)> class Test
[4] pry(main)*   include Bar
[4] pry(main)* end
=> Test
[5] pry(main)> Test.instance_methods.grep /stuff/
=> [:stuff]
[6] pry(main)> t = Test.new
=> #<Test:0x007fd68edcc7a8>
[7] pry(main)> t.stuff
in stuff
=> nil
```

**Comment by mvz** [comment] 2016-08-21 09:49
Ah, so `module_function` makes the instance method version private. That makes sense. We may actually want to not detect private methods as utility functions then, for the sake of consistency.

**Comment by adrianbn** [comment] 2016-08-21 17:14
That's a fair point; I do have a couple of private methods being flagged as utility functions as well.

**Comment by troessner** [comment] 2016-08-22 09:35
I could argue now that 

```Ruby
extend self
```

is a yet unnamed smell so far. Think about it: You're basically adding a method as a module function AND at the same time as a instance method.
Don't get me wrong, I've used this myself more than once in codebases, but for sure this doesn't sound like good architecture. Something along the lines of "SRP violation" but I'd have to give this a little bit more thought.
In any case, I'd consider this smelly already. 

>> We may actually want to not detect private methods as utility functions then, for the sake of consistency.

But ONLY when created via `module_function`, right?

**Comment by adrianbn** [comment] 2016-08-22 19:45
I'd say in any case. Using `extend self` with a private method results in the same behaviour for the class that includes the module as using `module_function`. From the module point of view the main difference is that the method is private.
```ruby
[1] pry(main)> module Foo
[1] pry(main)*   extend self
[1] pry(main)*   private
[1] pry(main)*   def priv_stuff
[1] pry(main)*     puts 'in stuff'
[1] pry(main)*   end
[1] pry(main)* end
=> :priv_stuff
[2] pry(main)> Foo.instance_methods
=> []
[3] pry(main)> Foo.methods.grep /priv_stuff/
=> []
[4] pry(main)> class Test
[4] pry(main)*   include Foo
[4] pry(main)* end
=> Test
[6] pry(main)> Test.instance_methods.grep /stuff/
=> []
[7] pry(main)> Test.methods.grep /stuff/
=> []
[10] pry(main)> t.priv_stuff
NoMethodError: private method `priv_stuff' called for #<Test:0x007ff742cc6b90>
from (pry):18:in `__pry__'
```

I think that for consistency the code above should not trigger UtilityFunction either.

**Comment by troessner** [comment] 2016-08-22 21:07
Ok, that is a long thread already, let's make sure that we are on the same page.

The problem is that Reek triggers UtilityFunction on 

```Ruby
module Foo
  extend self
  def do_stuff(arg); arg.method_call; end
end
```

but not on 

```Ruby
module Foo
  module_function
  def do_stuff(arg); arg.method_call; end
end
```

even though it **should** since module_function will create a private instance method.

That's the actual problem we're talking about, right?

**Comment by mvz** [comment] 2016-08-23 07:34
> That's the actual problem we're talking about, right?

Originally, it was the other way around.

Now it evolved into: since `module_function` creates a private instance method, and we don't flag methods created with `module_function`, shouldn't we allow private instance methods to be utility functions?

**Comment by troessner** [comment] 2016-08-23 07:41
You mean like, i dont know, having a [configuration flag](https://github.com/troessner/reek/blob/master/docs/Utility-Function.md#configuration) that disables the smell detector for private methods? ;)

**Comment by mvz** [comment] 2016-08-23 07:45
:laughing: well then, it should affect how we handle `module_function` as well then.

**Comment by troessner** [comment] 2016-08-23 10:01
But what exactly would you change?
Right now this:

```Ruby
module Foo
  module_function
  def do_stuff(arg); arg.method_call; end
end
```

is **not** reported which is the right thing. What is your concrete suggestion?

**Comment by adrianbn** [comment] 2016-08-23 10:10
If I'm not lost after all, I guess that to be consistent then this:
```ruby 
module Foo
  extend self
  private
  def priv_stuff(arg); arg.method_call; end
end
```

should not be reported either, but I just tested and it is.

**Comment by troessner** [comment] 2016-08-23 11:30
I'm hesitant with this. 

This

```Ruby
module Foo
  extend self
  private
  def priv_stuff(arg); arg.method_call; end
end
```

is not the same as 

```Ruby
module Foo
  module_function
  def do_stuff(arg); arg.method_call; end
end
```

In the `extend self` case you're explicitly creating an instance method. And you're making it private. Again, explicitly. `module_function` is doing all of this implicitly. 

I agree that the result **looks** similar, but the way to get there is so different that I can't see the need for consistency. 

But it's not just that: I also don't think that the result is the same thing from a user perspective since probably a lot of users of `module_function` are not aware that this creates a private instance method as well since it's implicit.

So from an "how do I intend to use this method" POV the explicit "extend self" version is majorly different to the implicit one. The explicit one says "here's a method and I intend to use it as instance method AND as module function".

So in this edge case, the syntax influences semantics.

I believe the current way we report it is fine and we should not patch Reek.

**Comment by troessner** [comment] 2016-11-12 20:33
I think this has been discussed extensively, closing.

**Closed by troessner** 2016-11-12 20:33 UTC
Labels: discussion, documentation
