### ISSUE TITLE
random test failures for rbx-2

### ISSUE THREAD

**Issue by beanieboi** [troessner/reek#507] opened 2015-05-08 10:05 UTC
sometimes Travis fails to execute our tests on rbx-2.

this is the stacktrace for the error:

```
(::) failed steps (::)
Exit status was 6 but expected it to be 0. Output:
Abort!
ruby(_ZN8rubinius5abortEv+0x77) [0x5cf427]
ruby() [0x5c6b22]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb5846) [0x7f03d6547846]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb5873) [0x7f03d6547873]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb596e) [0x7f03d654796e]
ruby(_ZN8rubinius9TypeError5raiseENS_11object_typeEPNS_6ObjectEPKc+0x4f) [0x5ceeaf]
ruby(_ZN8rubinius7console8Response3runEPNS_5StateE+0x3dd) [0x5c4f5d]
ruby(_ZN8rubinius14InternalThread3runEPv+0xbb) [0x5f418b]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7e9a) [0x7f03d69c0e9a]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f03d5fb12ed]
[BUG] Uncaught C++ internal exception
So sorry, it appears that you've encountered an internal
bug. Please report this on the rubinius issue tracker.
Include the following backtrace in the issue:
The Rubinius process is aborting with signal: SIGABRT
--- begin system info ---
sysname: Linux
nodename: testing-worker-linux-docker-f7e4e1d8-3256-linux-7
release: 3.13.0-40-generic
version: #69-Ubuntu SMP Thu Nov 13 17:53:56 UTC 2014
machine: x86_64
--- end system info ---
--- begin rubinius info ---
user: travis
pid: 5217
program name: rbx
version: 2.5.3
ruby version: 2.1.0
release date: 2015-04-28
build revision: 2482b0937ddb24ee97549b9654ec5269b7cd0579
llvm version: 3.4
jit status: enabled
--- end rubinius info ---
--- begin system backtrace ---
ruby() [0x69ac2c]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xfcb0) [0x7f03d69c8cb0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x35) [0x7f03d5ef30d5]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x17b) [0x7f03d5ef683b]
ruby(_ZN8rubinius5abortEv+0x7c) [0x5cf42c]
ruby() [0x5c6b22]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb5846) [0x7f03d6547846]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb5873) [0x7f03d6547873]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb596e) [0x7f03d654796e]
ruby(_ZN8rubinius9TypeError5raiseENS_11object_typeEPNS_6ObjectEPKc+0x4f) [0x5ceeaf]
ruby(_ZN8rubinius7console8Response3runEPNS_5StateE+0x3dd) [0x5c4f5d]
ruby(_ZN8rubinius14InternalThread3runEPv+0xbb) [0x5f418b]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7e9a) [0x7f03d69c0e9a]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f03d5fb12ed]
--- end system backtrace ---
--- begin Ruby backtraces ---
--- Thread 1 backtrace ---
Rubinius::CodeLoader#load_file in kernel/delta/code_loader.rb:175 (+48)
Rubinius::CodeLoader#require in kernel/common/code_loader.rb:128 (+64)
Rubinius::CodeLoader.require in kernel/common/code_loader.rb:241 (+35)
Kernel#require in kernel/common/kernel.rb:756 (+9)
Object#__script__ in /home/vagrant/devel/rubinius-2.5.3/staging/rubinius/2.5.3/runtime/gems/rubinius-compiler-2.3.1/lib/rubinius/compiler.rb:5 (+44)
Rubinius::CodeLoader#require_compiled in kernel/delta/code_loader.rb:37 (+83)
Rubinius::CodeLoader.require_compiled in kernel/delta/code_loader.rb:148 (+40)
__block__ in kernel/delta/code_loader.rb:139 (+26)
Rubinius::ToolSets.create in /home/vagrant/devel/rubinius-2.5.3/staging/rubinius/2.5.3/runtime/gems/rubinius-toolset-2.3.1/lib/rubinius/toolset.rb:21 (+123)
Rubinius::CodeLoader.load_compiler in kernel/delta/code_loader.rb:136 (+49)
Rubinius::Loader#load_compiler in kernel/loader.rb:553 (+18)
Rubinius::Loader#main in kernel/loader.rb:799 (+33)
--- Thread 7 backtrace ---
__block__ in kernel/delta/console.rb:17 (+5)
Proc#call in kernel/bootstrap/proc.rb:0 (+204)
Thread#__run__ in kernel/bootstrap/thread.rb:356 (+117)
--- end Ruby backtraces ---
 (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/reek_steps.rb:26:in `/^it succeeds$/'
features/reports/reports.feature:107:in `Then it succeeds'
features/reports/reports.feature:99:in `Then it succeeds'
Failing Scenarios:
cucumber features/reports/reports.feature:107 # Scenario Outline: --no-empty-headings turns off headings for fragrant files, Examples (#1)
71 scenarios (1 failed, 70 passed)
291 steps (1 failed, 1 skipped, 289 passed)
5m5.852s
The command "bundle exec rake" exited with 1.
```

**Comment by mvz** [comment] 2015-05-08 18:40
This seems to be an error internal to Rubinius. We may be better off filing a bug there. I'm installing Rubinius 2.5.3 right no to see if I can reproduce the crash.

**Comment by troessner** [comment] 2015-05-31 08:24
Seems like nobody is on this -> closing.

Feel free to re-open when re-starting the work on that.

**Closed by troessner** 2015-05-31 08:24 UTC
Labels: defect

**Comment by mvz** [comment] 2015-05-31 13:42
Ah, I neglected mentioning here that I did file a bug report with rubinius and it was fixed. See https://github.com/rubinius/rubinius/issues/3394.

**Comment by troessner** [comment] 2015-05-31 13:47
Even better!.;)
